internal.protocol: ipv4 ipv6
internal: end0 port = 1080
# send out through... can be an IP or an interface
external.protocol: ipv4 ipv6
external: wg0
# for user auth run as this user
user.privileged:   root
# otherwise run as this user
user.unprivileged: nobody
# auth with user login, passwd
# socksmethod:       username
# no authentication
clientmethod: none
socksmethod: none
# log to stdout
logoutput:         /dev/stdout
#debug: 1
# allow everyone from everywhere so long as they auth, log errors
client pass {
    from: 0/0 to: 0/0
    log: error # connect disconnect iooperation
}
# allow everyone from everywhere so long as they auth, log errors
socks pass {
    from: 0/0 to: 0/0
    command: bind connect udpassociate bindreply udpreply
    log: error # connect disconnect iooperation
}
